---
- name: Deploy collapsed-spine SR Linux nodes
  hosts: srl
  gather_facts: false
  roles:
    - role: srl_config

- name: Deploy collapsed-spine Linux endpoints
  hosts: linux_clients
  gather_facts: false
  roles:
    - role: linux_endpoint
