# s2: active-backup bond (primary eth2) to leaf2+leaf3, vlan 10 untagged.
interfaces:
  bond0:
    ipv4:
    - 172.16.10.2/24
bonds:
  bond0:
    mode: active-backup
    primary: eth2
    miimon: 100
    members:
    - eth1
    - eth2
routes:
- {family: ipv4, to: 172.16.20.0/24, via: 172.16.10.254, dev: bond0}
- {family: ipv4, to: 172.16.30.0/24, via: 172.16.10.254, dev: bond0}
- {family: ipv4, to: 172.16.92.0/22, via: 172.16.10.254, dev: bond0}
endpoint_ipv4_ping_targets:
- 172.16.10.254
- 172.16.10.1
- target: 172.16.30.6
  source: 172.16.10.2
